name = "COBTSExperiments"
uuid = "427fb70d-7af8-446f-9b10-34ec1bf19287"
authors = ["Arec <jamgochian95@gmail.com>"]
version = "0.1.0"

[deps]
CMCTS = "ff16bef5-90ca-4cd7-8044-bbffdeb5f989"
COTS = "f13cc095-4163-4f2d-bf68-c3de5b817b94"
CPOMCPOW = "b8155725-659d-4a2a-8aa1-b2cacdb9031f"
CPOMDPs = "b333230a-c79e-4dbf-bcff-ea8d21aa5ebd"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
POMDPGifs = "7f35509c-0cb9-11e9-0708-2928828cdbb7"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RoombaPOMDPs = "fe2df5ea-4d44-4e5a-a895-9dbc87b19b37"
SpillpointPOMDP = "c0d8999d-0f66-4d3f-9af4-6d8207e3a4b3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
