name = "COTS"
uuid = "f13cc095-4163-4f2d-bf68-c3de5b817b94"
authors = ["Arec <jamgochian95@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CPOMDPs = "b333230a-c79e-4dbf-bcff-ea8d21aa5ebd"
D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
